# Generated by Django 4.2 on 2024-09-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
    ]
